// Generated by CIRCT firtool-1.114.1
module SyncMux(
  input         clk,
                clr_n,
  input  [15:0] x1,
                x2,
  input         addr,
  output [15:0] y
);

  wire        _asyncReset_T = ~clr_n;
  reg  [15:0] out_value;
  always @(posedge clk or posedge _asyncReset_T) begin
    if (_asyncReset_T)
      out_value <= 16'h0;
    else
      out_value <= addr ? x2 : x1;
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (_asyncReset_T)
        out_value = 16'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign y = out_value;
endmodule


// ----- 8< ----- FILE "verification/cover/layers-SyncMux-Verification-Cover.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.1
`include "verification/layers-SyncMux-Verification.sv"
`ifndef layers_SyncMux_Verification_Cover
`define layers_SyncMux_Verification_Cover
`endif // layers_SyncMux_Verification_Cover

// ----- 8< ----- FILE "verification/assume/layers-SyncMux-Verification-Assume.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.1
`include "verification/layers-SyncMux-Verification.sv"
`ifndef layers_SyncMux_Verification_Assume
`define layers_SyncMux_Verification_Assume
`endif // layers_SyncMux_Verification_Assume

// ----- 8< ----- FILE "verification/assert/layers-SyncMux-Verification-Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.1
`include "verification/layers-SyncMux-Verification.sv"
`ifndef layers_SyncMux_Verification_Assert
`define layers_SyncMux_Verification_Assert
`endif // layers_SyncMux_Verification_Assert

// ----- 8< ----- FILE "verification/layers-SyncMux-Verification.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.1
`ifndef layers_SyncMux_Verification
`define layers_SyncMux_Verification
`endif // layers_SyncMux_Verification