/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post105, git sha1 b5170e139) */

(* generator = "Amaranth" *)
module innerMedian(clr_n, arr_0, arr_1, arr_2, arr_3, arr_4, arr_5, arr_6, arr_7, arr_8, med, clk);
  wire [71:0] arr;
  input [7:0] arr_0;
  wire [7:0] arr_0;
  input [7:0] arr_1;
  wire [7:0] arr_1;
  input [7:0] arr_2;
  wire [7:0] arr_2;
  input [7:0] arr_3;
  wire [7:0] arr_3;
  input [7:0] arr_4;
  wire [7:0] arr_4;
  input [7:0] arr_5;
  wire [7:0] arr_5;
  input [7:0] arr_6;
  wire [7:0] arr_6;
  input [7:0] arr_7;
  wire [7:0] arr_7;
  input [7:0] arr_8;
  wire [7:0] arr_8;
  input clk;
  wire clk;
  wire \clk$12 ;
  input clr_n;
  wire clr_n;
  wire \clr_n$13 ;
  output [7:0] med;
  wire [7:0] med;
  wire [7:0] \med$15 ;
  \innerMedian.med$16  \med$16  (
    .clk(clk),
    .clr_n(clr_n),
    .med(med),
    .\port$0$12 (arr_1),
    .\port$0$20 (arr_2),
    .\port$0$28 (arr_3),
    .\port$0$36 (arr_4),
    .\port$0$4 (arr_0),
    .\port$0$44 (arr_5),
    .\port$0$52 (arr_6),
    .\port$0$60 (arr_7),
    .\port$0$68 (arr_8)
  );
  assign \clk$12  = clk;
  assign \clr_n$13  = clr_n;
  assign arr = { arr_8, arr_7, arr_6, arr_5, arr_4, arr_3, arr_2, arr_1, arr_0 };
  assign \med$15  = med;
endmodule

(* generator = "Amaranth" *)
module \innerMedian.med$16 (clr_n, \port$0$4 , \port$0$12 , \port$0$20 , \port$0$28 , \port$0$36 , \port$0$44 , \port$0$52 , \port$0$60 , \port$0$68 , med, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire [7:0] \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire [4:0] \$17 ;
  wire [4:0] \$18 ;
  wire \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire \$21 ;
  wire [4:0] \$22 ;
  wire [2:0] \$23 ;
  wire \$24 ;
  wire \$25 ;
  wire \$26 ;
  wire \$27 ;
  wire \$28 ;
  wire \$29 ;
  wire \$3 ;
  wire \$30 ;
  wire [4:0] \$31 ;
  wire [4:0] \$32 ;
  wire [4:0] \$33 ;
  wire [5:0] \$34 ;
  wire \$35 ;
  wire \$36 ;
  wire \$37 ;
  wire \$38 ;
  wire \$39 ;
  wire \$4 ;
  wire [4:0] \$40 ;
  wire \$41 ;
  wire [4:0] \$42 ;
  wire \$43 ;
  wire \$44 ;
  wire [4:0] \$45 ;
  wire [5:0] \$46 ;
  wire [3:0] \$47 ;
  wire [4:0] \$48 ;
  wire \$49 ;
  wire \$5 ;
  wire \$50 ;
  wire [4:0] \$51 ;
  wire [5:0] \$52 ;
  wire [3:0] \$53 ;
  reg [2:0] \$54 ;
  reg \$55 ;
  reg \$56 ;
  reg \$57 ;
  reg \$58 ;
  wire [71:0] \$59 ;
  wire \$6 ;
  reg [3:0] \$60 ;
  reg \$61 ;
  reg \$62 ;
  reg [2:0] \$63 ;
  reg [3:0] \$64 ;
  reg [3:0] \$65 ;
  reg [3:0] \$66 ;
  reg [7:0] \$67 ;
  reg \$68 ;
  reg \$69 ;
  wire \$7 ;
  reg [1:0] \$70 ;
  reg \$71 ;
  reg \$72 ;
  wire [7:0] \$74 ;
  wire \$8 ;
  wire \$9 ;
  wire [71:0] arr;
  reg [2:0] bit_counter = 3'h7;
  reg [7:0] buffer = 8'h00;
  input clk;
  wire clk;
  wire \clk$1 ;
  wire \clk$4 ;
  wire \clk$5 ;
  wire \clk$6 ;
  input clr_n;
  wire clr_n;
  reg \clr_n$23  = 1'h1;
  reg \clr_n$24  = 1'h1;
  reg \clr_n$25  = 1'h1;
  wire en_write;
  reg [3:0] fifo_counter = 4'h8;
  reg [2:0] fsm_state = 3'h0;
  wire [7:0] head;
  reg in_work_n = 1'h1;
  reg [3:0] index = 4'h0;
  reg is_low;
  output [7:0] med;
  reg [7:0] med;
  reg [71:0] num_buffer = 72'h000000000000000000;
  reg [3:0] offset = 4'h8;
  reg pop = 1'h0;
  reg \pop$35  = 1'h0;
  reg \pop$36  = 1'h0;
  input [7:0] \port$0$12 ;
  wire [7:0] \port$0$12 ;
  input [7:0] \port$0$20 ;
  wire [7:0] \port$0$20 ;
  input [7:0] \port$0$28 ;
  wire [7:0] \port$0$28 ;
  input [7:0] \port$0$36 ;
  wire [7:0] \port$0$36 ;
  input [7:0] \port$0$4 ;
  wire [7:0] \port$0$4 ;
  input [7:0] \port$0$44 ;
  wire [7:0] \port$0$44 ;
  input [7:0] \port$0$52 ;
  wire [7:0] \port$0$52 ;
  input [7:0] \port$0$60 ;
  wire [7:0] \port$0$60 ;
  input [7:0] \port$0$68 ;
  wire [7:0] \port$0$68 ;
  reg push = 1'h0;
  reg \push$33  = 1'h0;
  reg \push$34  = 1'h0;
  wire [7:0] rd_data;
  wire [7:0] \rd_data$20 ;
  wire [7:0] \rd_data$21 ;
  wire rst;
  reg [1:0] stable_counter = 2'h2;
  reg [3:0] total = 4'h9;
  reg [7:0] wr_data;
  reg [7:0] \wr_data$16 ;
  reg [7:0] \wr_data$18 ;
  assign \$25  = stable_counter == 2'h2;
  assign \$26  = total == 3'h5;
  assign \$27  = index == 3'h4;
  assign \$28  = \$26  & \$27 ;
  assign \$29  = offset == 1'h1;
  assign \$30  = \$28  & \$29 ;
  assign \$31  = index + offset;
  assign \$32  = index + offset;
  assign \$33  = total - index;
  assign \$34  = $signed(\$33 ) - $signed({ 1'h0, offset });
  assign \$35  = total == 3'h5;
  assign \$36  = index == 3'h4;
  assign \$37  = \$35  & \$36 ;
  assign \$38  = offset == 1'h1;
  assign \$39  = \$37  & \$38 ;
  assign \$40  = offset + index;
  assign \$41  = \$40  <= 3'h4;
  assign \$42  = fifo_counter - 1'h1;
  assign \$43  = fifo_counter == 2'h2;
  assign \$44  = fifo_counter == 1'h1;
  assign \$45  = total - index;
  assign \$46  = $signed(\$45 ) - $signed(2'h1);
  assign \$47  = bit_counter - 1'h1;
  assign \$48  = fifo_counter - 1'h1;
  assign \$49  = fifo_counter == 2'h2;
  assign \$50  = fifo_counter == 1'h1;
  assign \$51  = total - index;
  assign \$52  = $signed(\$51 ) - $signed(2'h1);
  assign \$53  = bit_counter - 1'h1;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) fsm_state <= 3'h0;
    else fsm_state <= \$54 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) \clr_n$23  <= 1'h1;
    else \clr_n$23  <= \$55 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) \clr_n$24  <= 1'h1;
    else \clr_n$24  <= \$56 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) \clr_n$25  <= 1'h1;
    else \clr_n$25  <= \$57 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) in_work_n <= 1'h1;
    else in_work_n <= \$58 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) num_buffer <= 72'h000000000000000000;
    else num_buffer <= \$59 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) fifo_counter <= 4'h8;
    else fifo_counter <= \$60 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) push <= 1'h0;
    else push <= \$61 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) pop <= 1'h0;
    else pop <= \$62 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) bit_counter <= 3'h7;
    else bit_counter <= \$63 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) offset <= 4'h8;
    else offset <= \$64 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) index <= 4'h0;
    else index <= \$65 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) total <= 4'h9;
    else total <= \$66 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) buffer <= 8'h00;
    else buffer <= \$67 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) \push$33  <= 1'h0;
    else \push$33  <= \$68 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) \push$34  <= 1'h0;
    else \push$34  <= \$69 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) stable_counter <= 2'h2;
    else stable_counter <= \$70 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) \pop$35  <= 1'h0;
    else \pop$35  <= \$71 ;
  always @(posedge clk, negedge clr_n)
    if (!clr_n) \pop$36  <= 1'h0;
    else \pop$36  <= \$72 ;
  assign rst = ~ clr_n;
  assign \$74  = fifo_counter * 4'h8;
  assign \$1  = num_buffer >> \$74 ;
  assign \$2  = rd_data >> bit_counter;
  assign \$3  = ~ \$2 ;
  assign \$4  = ! stable_counter;
  assign \$5  = stable_counter == 2'h2;
  assign \$6  = rd_data >> bit_counter;
  assign \$7  = ~ \$6 ;
  assign \$8  = ! fsm_state;
  assign \$9  = fsm_state == 1'h1;
  assign \$10  = fsm_state == 2'h2;
  assign \$11  = fsm_state == 2'h3;
  assign \$12  = fsm_state == 3'h4;
  assign \$13  = fsm_state == 3'h5;
  assign \$14  = fsm_state == 3'h6;
  assign \$15  = fifo_counter == 1'h1;
  assign \$16  = ! fifo_counter;
  assign \$17  = fifo_counter - 1'h1;
  assign \$18  = offset + is_low;
  assign \$19  = ~ is_low;
  assign \$20  = fifo_counter == 1'h1;
  assign \$21  = ! fifo_counter;
  assign \$22  = fifo_counter - 1'h1;
  assign \$23  = stable_counter - 1'h1;
  assign \$24  = ! stable_counter;
  \innerMedian.med$16.high_fifo  high_fifo (
    .clr_n(\clr_n$25 ),
    .high_fifo_sync_clk(clk),
    .memory_r_en(\pop$36 ),
    .memory_w_en(\push$33 ),
    .rd_data(\rd_data$21 ),
    .wr_data(\wr_data$16 )
  );
  \innerMedian.med$16.init_fifo  init_fifo (
    .clr_n(\clr_n$23 ),
    .head(head),
    .init_fifo_sync_clk(clk),
    .memory_r_en(pop),
    .memory_w_en(push),
    .rd_data(rd_data),
    .wr_data(wr_data)
  );
  \innerMedian.med$16.low_fifo  low_fifo (
    .clr_n(\clr_n$24 ),
    .low_fifo_sync_clk(clk),
    .memory_r_en(\pop$35 ),
    .memory_w_en(\push$34 ),
    .rd_data(\rd_data$20 ),
    .wr_data(\wr_data$18 )
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    med = 8'h00;
    casez (fsm_state)
      3'h0:
          med = head;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    wr_data = 8'h00;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          wr_data = \$1 ;
      3'h3:
          /* empty */;
      3'h4:
          /* empty */;
      3'h5:
          wr_data = \rd_data$20 ;
      3'h6:
          wr_data = \rd_data$21 ;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    is_low = 1'h0;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          is_low = \$3 ;
      3'h4:
          if (\$4 ) begin
          end else if (\$5 ) begin
            is_low = \$7 ;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \wr_data$16  = 8'h00;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          \wr_data$16  = buffer;
      3'h4:
          if (\$4 ) begin
          end else if (\$5 ) begin
            \wr_data$16  = buffer;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \wr_data$18  = 8'h00;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          \wr_data$18  = buffer;
      3'h4:
          if (\$4 ) begin
          end else if (\$5 ) begin
            \wr_data$18  = buffer;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$54  = fsm_state;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\clr_n$23 ) begin
            \$54  = 3'h2;
          end
      3'h2:
          if (\$16 ) begin
            \$54  = 3'h3;
          end
      3'h3:
          if (\$21 ) begin
            \$54  = 3'h4;
          end
      3'h4:
          if (\$24 ) begin
            (* full_case = 32'd1 *)
            if (\$30 ) begin
              \$54  = 3'h0;
            end else if (\pop$35 ) begin
              \$54  = 3'h5;
            end else begin
              \$54  = 3'h6;
            end
          end
      3'h5:
          if (\$44 ) begin
            \$54  = 3'h3;
          end
      3'h6:
          if (\$50 ) begin
            \$54  = 3'h3;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$55  = \clr_n$23 ;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          (* full_case = 32'd1 *)
          if (\clr_n$23 ) begin
          end else begin
            \$55  = 1'h1;
          end
      3'h2:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          (* full_case = 32'd1 *)
          if (\$24 ) begin
          end else if (\$25 ) begin
            \$55  = 1'h0;
          end else begin
            \$55  = 1'h1;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$56  = \clr_n$24 ;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          (* full_case = 32'd1 *)
          if (\clr_n$23 ) begin
          end else begin
            \$56  = 1'h1;
          end
      3'h2:
        begin
          if (\$15 ) begin
            \$56  = 1'h0;
          end
          if (\$16 ) begin
            \$56  = 1'h1;
          end
        end
      3'h3:
          /* empty */;
      3'h4:
          /* empty */;
      3'h5:
        begin
          if (\$43 ) begin
            \$56  = 1'h0;
          end
          if (\$44 ) begin
            \$56  = 1'h1;
          end
        end
      3'h6:
        begin
          if (\$49 ) begin
            \$56  = 1'h0;
          end
          if (\$50 ) begin
            \$56  = 1'h1;
          end
        end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$57  = \clr_n$25 ;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          (* full_case = 32'd1 *)
          if (\clr_n$23 ) begin
          end else begin
            \$57  = 1'h1;
          end
      3'h2:
        begin
          if (\$15 ) begin
            \$57  = 1'h0;
          end
          if (\$16 ) begin
            \$57  = 1'h1;
          end
        end
      3'h3:
          /* empty */;
      3'h4:
          /* empty */;
      3'h5:
        begin
          if (\$43 ) begin
            \$57  = 1'h0;
          end
          if (\$44 ) begin
            \$57  = 1'h1;
          end
        end
      3'h6:
        begin
          if (\$49 ) begin
            \$57  = 1'h0;
          end
          if (\$50 ) begin
            \$57  = 1'h1;
          end
        end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$58  = in_work_n;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          if (\$24 ) begin
            if (\$30 ) begin
              \$58  = 1'h1;
            end
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$60  = fifo_counter;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\clr_n$23 ) begin
            \$60  = 4'h8;
          end
      3'h2:
          (* full_case = 32'd1 *)
          if (\$16 ) begin
            \$60  = 4'h8;
          end else begin
            \$60  = \$17 [3:0];
          end
      3'h3:
          (* full_case = 32'd1 *)
          if (\$21 ) begin
          end else begin
            \$60  = \$22 [3:0];
          end
      3'h4:
          if (\$24 ) begin
            (* full_case = 32'd1 *)
            if (\$30 ) begin
            end else if (\pop$35 ) begin
              \$60  = offset;
            end else begin
              \$60  = \$34 [3:0];
            end
          end
      3'h5:
        begin
          \$60  = \$42 [3:0];
          if (\$44 ) begin
            \$60  = \$46 [3:0];
          end
        end
      3'h6:
        begin
          \$60  = \$48 [3:0];
          if (\$50 ) begin
            \$60  = \$52 [3:0];
          end
        end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$61  = push;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\clr_n$23 ) begin
            \$61  = 1'h1;
          end
      3'h2:
          if (\$16 ) begin
            \$61  = 1'h0;
          end
      3'h3:
          /* empty */;
      3'h4:
          if (\$24 ) begin
            (* full_case = 32'd1 *)
            if (\$30 ) begin
            end else if (\pop$35 ) begin
              \$61  = 1'h1;
            end else begin
              \$61  = 1'h1;
            end
          end
      3'h5:
          if (\$44 ) begin
            \$61  = 1'h0;
          end
      3'h6:
          if (\$50 ) begin
            \$61  = 1'h0;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$62  = pop;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          if (\$15 ) begin
            \$62  = 1'h1;
          end
      3'h3:
          if (\$20 ) begin
            \$62  = 1'h0;
          end
      3'h4:
          /* empty */;
      3'h5:
          if (\$43 ) begin
            \$62  = 1'h1;
          end
      3'h6:
          if (\$49 ) begin
            \$62  = 1'h1;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$63  = bit_counter;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          if (\$16 ) begin
            \$63  = 3'h7;
          end
      3'h3:
          /* empty */;
      3'h4:
          /* empty */;
      3'h5:
          if (\$44 ) begin
            \$63  = \$47 [2:0];
          end
      3'h6:
          if (\$50 ) begin
            \$63  = \$53 [2:0];
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$64  = offset;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          if (\$16 ) begin
            \$64  = 4'h0;
          end
      3'h3:
          \$64  = \$18 [3:0];
      3'h4:
          /* empty */;
      3'h5:
          if (\$44 ) begin
            \$64  = 4'h0;
          end
      3'h6:
          if (\$50 ) begin
            \$64  = 4'h0;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$65  = index;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          if (\$16 ) begin
            \$65  = 4'h0;
          end
      3'h3:
          /* empty */;
      3'h4:
          if (\$24 ) begin
            (* full_case = 32'd1 *)
            if (\$30 ) begin
            end else if (\pop$35 ) begin
            end else begin
              \$65  = \$32 [3:0];
            end
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$66  = total;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          if (\$16 ) begin
            \$66  = 4'h9;
          end
      3'h3:
          /* empty */;
      3'h4:
          if (\$24 ) begin
            if (\$30 ) begin
            end else if (\pop$35 ) begin
              \$66  = \$31 [3:0];
            end
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$67  = buffer;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          \$67  = rd_data;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$68  = \push$33 ;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          \$68  = \$19 ;
      3'h4:
          if (\$24 ) begin
          end else if (\$25 ) begin
            \$68  = 1'h0;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$69  = \push$34 ;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          \$69  = is_low;
      3'h4:
          if (\$24 ) begin
          end else if (\$25 ) begin
            \$69  = 1'h0;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$70  = stable_counter;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          if (\$21 ) begin
            \$70  = 2'h2;
          end
      3'h4:
          \$70  = \$23 [1:0];
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$71  = \pop$35 ;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          (* full_case = 32'd1 *)
          if (\$24 ) begin
            if (\$30 ) begin
              \$71  = 1'h0;
            end
          end else if (\$25 ) begin
          end else begin
            (* full_case = 32'd1 *)
            if (\$39 ) begin
              \$71  = 1'h1;
            end else if (\$41 ) begin
            end else begin
              \$71  = 1'h1;
            end
          end
      3'h5:
          if (\$43 ) begin
            \$71  = 1'h0;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$72  = \pop$36 ;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h2:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          (* full_case = 32'd1 *)
          if (\$24 ) begin
          end else if (\$25 ) begin
          end else begin
            if (\$39 ) begin
            end else if (\$41 ) begin
              \$72  = 1'h1;
            end
          end
      3'h5:
          /* empty */;
      3'h6:
          if (\$49 ) begin
            \$72  = 1'h0;
          end
    endcase
  end
  assign \clk$1  = clk;
  assign \clk$4  = clk;
  assign \clk$5  = clk;
  assign \clk$6  = clk;
  assign en_write = 1'h0;
  assign arr = { \port$0$68 , \port$0$60 , \port$0$52 , \port$0$44 , \port$0$36 , \port$0$28 , \port$0$20 , \port$0$12 , \port$0$4  };
  assign \$59  = num_buffer;
endmodule

(* generator = "Amaranth" *)
module \innerMedian.med$16.high_fifo (rd_data, wr_data, clr_n, memory_w_en, memory_r_en, high_fifo_sync_clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$2  = 0;
  wire \$1 ;
  wire [4:0] \$2 ;
  wire \$3 ;
  wire [4:0] \$4 ;
  wire \$5 ;
  reg [3:0] \$6 ;
  reg [3:0] \$7 ;
  reg [3:0] \$8 ;
  reg [3:0] \$9 ;
  wire clk;
  input clr_n;
  wire clr_n;
  wire [7:0] head;
  input high_fifo_sync_clk;
  wire high_fifo_sync_clk;
  wire high_fifo_sync_rst;
  wire [3:0] memory_r_addr;
  reg [3:0] \memory_r_addr$17  = 4'h0;
  wire [7:0] memory_r_data;
  wire [7:0] \memory_r_data$14 ;
  input memory_r_en;
  wire memory_r_en;
  reg [3:0] memory_w_addr = 4'h0;
  reg [7:0] memory_w_data;
  input memory_w_en;
  wire memory_w_en;
  wire pop;
  wire push;
  reg [3:0] r_addr = 4'h0;
  output [7:0] rd_data;
  wire [7:0] rd_data;
  reg [3:0] w_addr = 4'h0;
  input [7:0] wr_data;
  wire [7:0] wr_data;
  reg [7:0] memory [8:0];
  initial begin
    memory[0] = 8'h00;
    memory[1] = 8'h00;
    memory[2] = 8'h00;
    memory[3] = 8'h00;
    memory[4] = 8'h00;
    memory[5] = 8'h00;
    memory[6] = 8'h00;
    memory[7] = 8'h00;
    memory[8] = 8'h00;
  end
  always @(posedge high_fifo_sync_clk) begin
    if (memory_w_en)
      memory[memory_w_addr] <= memory_w_data;
  end
  reg [7:0] _0_;
  always @(posedge high_fifo_sync_clk) begin
    if (memory_r_en) begin
      _0_ <= memory[\memory_r_addr$17 ];
      if (memory_w_en && \memory_r_addr$17  == memory_w_addr)
        _0_ <= memory_w_data;
    end
  end
  assign rd_data = _0_;
  assign head = memory[4'h0];
  assign high_fifo_sync_rst = ~ clr_n;
  assign \$1  = w_addr == 4'h8;
  assign \$2  = w_addr + 1'h1;
  assign \$3  = r_addr == 4'h8;
  assign \$4  = r_addr + 1'h1;
  assign \$5  = ~ clr_n;
  always @(posedge high_fifo_sync_clk)
    memory_w_addr <= \$6 ;
  always @(posedge high_fifo_sync_clk)
    w_addr <= \$7 ;
  always @(posedge high_fifo_sync_clk)
    \memory_r_addr$17  <= \$8 ;
  always @(posedge high_fifo_sync_clk)
    r_addr <= \$9 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    memory_w_data = 8'h00;
    if (memory_w_en) begin
      memory_w_data = wr_data;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$6  = w_addr;
    if (\$5 ) begin
      \$6  = 4'h0;
    end
    if (high_fifo_sync_rst) begin
      \$6  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$7  = w_addr;
    if (memory_w_en) begin
      (* full_case = 32'd1 *)
      if (\$1 ) begin
        \$7  = 4'h0;
      end else begin
        \$7  = \$2 [3:0];
      end
    end
    if (high_fifo_sync_rst) begin
      \$7  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$8  = r_addr;
    if (\$5 ) begin
      \$8  = 4'h0;
    end
    if (high_fifo_sync_rst) begin
      \$8  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$9  = r_addr;
    if (memory_r_en) begin
      (* full_case = 32'd1 *)
      if (\$3 ) begin
        \$9  = 4'h0;
      end else begin
        \$9  = \$4 [3:0];
      end
    end
    if (high_fifo_sync_rst) begin
      \$9  = 4'h0;
    end
  end
  assign clk = high_fifo_sync_clk;
  assign memory_r_addr = 4'h0;
  assign memory_r_data = head;
  assign push = memory_w_en;
  assign pop = memory_r_en;
  assign \memory_r_data$14  = rd_data;
endmodule

(* generator = "Amaranth" *)
module \innerMedian.med$16.init_fifo (head, rd_data, wr_data, clr_n, memory_w_en, memory_r_en, init_fifo_sync_clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$3  = 0;
  wire \$1 ;
  wire [4:0] \$2 ;
  wire \$3 ;
  wire [4:0] \$4 ;
  wire \$5 ;
  reg [3:0] \$6 ;
  reg [3:0] \$7 ;
  reg [3:0] \$8 ;
  reg [3:0] \$9 ;
  wire clk;
  input clr_n;
  wire clr_n;
  output [7:0] head;
  wire [7:0] head;
  input init_fifo_sync_clk;
  wire init_fifo_sync_clk;
  wire init_fifo_sync_rst;
  wire [3:0] memory_r_addr;
  reg [3:0] \memory_r_addr$17  = 4'h0;
  wire [7:0] memory_r_data;
  wire [7:0] \memory_r_data$14 ;
  input memory_r_en;
  wire memory_r_en;
  reg [3:0] memory_w_addr = 4'h0;
  reg [7:0] memory_w_data;
  input memory_w_en;
  wire memory_w_en;
  wire pop;
  wire push;
  reg [3:0] r_addr = 4'h0;
  output [7:0] rd_data;
  wire [7:0] rd_data;
  reg [3:0] w_addr = 4'h0;
  input [7:0] wr_data;
  wire [7:0] wr_data;
  reg [7:0] memory [8:0];
  initial begin
    memory[0] = 8'h00;
    memory[1] = 8'h00;
    memory[2] = 8'h00;
    memory[3] = 8'h00;
    memory[4] = 8'h00;
    memory[5] = 8'h00;
    memory[6] = 8'h00;
    memory[7] = 8'h00;
    memory[8] = 8'h00;
  end
  always @(posedge init_fifo_sync_clk) begin
    if (memory_w_en)
      memory[memory_w_addr] <= memory_w_data;
  end
  reg [7:0] _0_;
  always @(posedge init_fifo_sync_clk) begin
    if (memory_r_en) begin
      _0_ <= memory[\memory_r_addr$17 ];
      if (memory_w_en && \memory_r_addr$17  == memory_w_addr)
        _0_ <= memory_w_data;
    end
  end
  assign rd_data = _0_;
  assign head = memory[4'h0];
  assign init_fifo_sync_rst = ~ clr_n;
  assign \$1  = w_addr == 4'h8;
  assign \$2  = w_addr + 1'h1;
  assign \$3  = r_addr == 4'h8;
  assign \$4  = r_addr + 1'h1;
  assign \$5  = ~ clr_n;
  always @(posedge init_fifo_sync_clk)
    memory_w_addr <= \$6 ;
  always @(posedge init_fifo_sync_clk)
    w_addr <= \$7 ;
  always @(posedge init_fifo_sync_clk)
    \memory_r_addr$17  <= \$8 ;
  always @(posedge init_fifo_sync_clk)
    r_addr <= \$9 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    memory_w_data = 8'h00;
    if (memory_w_en) begin
      memory_w_data = wr_data;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$6  = w_addr;
    if (\$5 ) begin
      \$6  = 4'h0;
    end
    if (init_fifo_sync_rst) begin
      \$6  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$7  = w_addr;
    if (memory_w_en) begin
      (* full_case = 32'd1 *)
      if (\$1 ) begin
        \$7  = 4'h0;
      end else begin
        \$7  = \$2 [3:0];
      end
    end
    if (init_fifo_sync_rst) begin
      \$7  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$8  = r_addr;
    if (\$5 ) begin
      \$8  = 4'h0;
    end
    if (init_fifo_sync_rst) begin
      \$8  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$9  = r_addr;
    if (memory_r_en) begin
      (* full_case = 32'd1 *)
      if (\$3 ) begin
        \$9  = 4'h0;
      end else begin
        \$9  = \$4 [3:0];
      end
    end
    if (init_fifo_sync_rst) begin
      \$9  = 4'h0;
    end
  end
  assign clk = init_fifo_sync_clk;
  assign memory_r_addr = 4'h0;
  assign memory_r_data = head;
  assign push = memory_w_en;
  assign pop = memory_r_en;
  assign \memory_r_data$14  = rd_data;
endmodule

(* generator = "Amaranth" *)
module \innerMedian.med$16.low_fifo (rd_data, wr_data, clr_n, memory_w_en, memory_r_en, low_fifo_sync_clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$4  = 0;
  wire \$1 ;
  wire [4:0] \$2 ;
  wire \$3 ;
  wire [4:0] \$4 ;
  wire \$5 ;
  reg [3:0] \$6 ;
  reg [3:0] \$7 ;
  reg [3:0] \$8 ;
  reg [3:0] \$9 ;
  wire clk;
  input clr_n;
  wire clr_n;
  wire [7:0] head;
  input low_fifo_sync_clk;
  wire low_fifo_sync_clk;
  wire low_fifo_sync_rst;
  wire [3:0] memory_r_addr;
  reg [3:0] \memory_r_addr$17  = 4'h0;
  wire [7:0] memory_r_data;
  wire [7:0] \memory_r_data$14 ;
  input memory_r_en;
  wire memory_r_en;
  reg [3:0] memory_w_addr = 4'h0;
  reg [7:0] memory_w_data;
  input memory_w_en;
  wire memory_w_en;
  wire pop;
  wire push;
  reg [3:0] r_addr = 4'h0;
  output [7:0] rd_data;
  wire [7:0] rd_data;
  reg [3:0] w_addr = 4'h0;
  input [7:0] wr_data;
  wire [7:0] wr_data;
  reg [7:0] memory [8:0];
  initial begin
    memory[0] = 8'h00;
    memory[1] = 8'h00;
    memory[2] = 8'h00;
    memory[3] = 8'h00;
    memory[4] = 8'h00;
    memory[5] = 8'h00;
    memory[6] = 8'h00;
    memory[7] = 8'h00;
    memory[8] = 8'h00;
  end
  always @(posedge low_fifo_sync_clk) begin
    if (memory_w_en)
      memory[memory_w_addr] <= memory_w_data;
  end
  reg [7:0] _0_;
  always @(posedge low_fifo_sync_clk) begin
    if (memory_r_en) begin
      _0_ <= memory[\memory_r_addr$17 ];
      if (memory_w_en && \memory_r_addr$17  == memory_w_addr)
        _0_ <= memory_w_data;
    end
  end
  assign rd_data = _0_;
  assign head = memory[4'h0];
  assign low_fifo_sync_rst = ~ clr_n;
  assign \$1  = w_addr == 4'h8;
  assign \$2  = w_addr + 1'h1;
  assign \$3  = r_addr == 4'h8;
  assign \$4  = r_addr + 1'h1;
  assign \$5  = ~ clr_n;
  always @(posedge low_fifo_sync_clk)
    memory_w_addr <= \$6 ;
  always @(posedge low_fifo_sync_clk)
    w_addr <= \$7 ;
  always @(posedge low_fifo_sync_clk)
    \memory_r_addr$17  <= \$8 ;
  always @(posedge low_fifo_sync_clk)
    r_addr <= \$9 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    memory_w_data = 8'h00;
    if (memory_w_en) begin
      memory_w_data = wr_data;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$6  = w_addr;
    if (\$5 ) begin
      \$6  = 4'h0;
    end
    if (low_fifo_sync_rst) begin
      \$6  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$7  = w_addr;
    if (memory_w_en) begin
      (* full_case = 32'd1 *)
      if (\$1 ) begin
        \$7  = 4'h0;
      end else begin
        \$7  = \$2 [3:0];
      end
    end
    if (low_fifo_sync_rst) begin
      \$7  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$8  = r_addr;
    if (\$5 ) begin
      \$8  = 4'h0;
    end
    if (low_fifo_sync_rst) begin
      \$8  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$9  = r_addr;
    if (memory_r_en) begin
      (* full_case = 32'd1 *)
      if (\$3 ) begin
        \$9  = 4'h0;
      end else begin
        \$9  = \$4 [3:0];
      end
    end
    if (low_fifo_sync_rst) begin
      \$9  = 4'h0;
    end
  end
  assign clk = low_fifo_sync_clk;
  assign memory_r_addr = 4'h0;
  assign memory_r_data = head;
  assign push = memory_w_en;
  assign pop = memory_r_en;
  assign \memory_r_data$14  = rd_data;
endmodule

